rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/documentdb_documentation/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_linux/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_fucshia/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_macos/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_server/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_apis/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_android/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_ios/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_client/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_dart/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_assets_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_web/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_isar_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_cli/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/documentdb/package/documentdb_windows/LICENSE
