name: 'documentdb_database_universe_scheme'
description: 'documentdb is program for help you, booster up your projects significants'
version: '0.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  database_universe: '^1.0.5'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  build_runner: 'any'
repository: 'https://github.com/{main_username_owner}/documentdb'
homepage: 'https://github.com/{main_username_owner}/documentdb'
issue_tracker: 'https://github.com/{main_username_owner}/documentdb/issues'
documentation: 'https://github.com/{main_username_owner}/documentdb/tree/main/docs'
funding:
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
