name: 'documentdb_database'
description: 'A sample command-line application.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  path: '^1.9.0'
  general_lib: '^0.0.62'
  database_universe: '^1.0.5'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  build_runner: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding: []
